[build]
command = "npm ci && npm run build:ssg"
publish = "dist/jorge-palacio/browser"

[build.environment]
NODE_VERSION = "20"

# SPA fallback (Angular router)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Cache agresivo para assets
[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
